/**
 * Mother MCP Types
 * 
 * IMPORTANT: Mother MCP is a CONSUMER of registry data, not the source.
 * Quality signals (downloads, stars, verified status) come FROM external
 * registries like the agent_skills_directory catalog. Mother fetches and
 * displays this data but does not generate or track it.
 * 
 * The canonical skill registry is:
 * https://github.com/dmgrok/agent_skills_directory
 */

// Agent types
export type AgentId = 'claude' | 'copilot' | 'codex' | 'generic';
export type AgentMode = 'auto' | 'claude' | 'copilot' | 'codex' | 'both';

export interface AgentProfile {
  id: AgentId;
  name: string;
  projectSkillPaths: string[];
  personalSkillPath: string;
  instructionsFile: string;
  customInstructionsPath: string;
}

// Registry types
export interface RegistrySource {
  url: string;
  priority: number;
  auth?: string;
}

export interface SkillTrigger {
  packages?: string[];
  files?: string[];
  readme_keywords?: string[];
  manual_only?: boolean;
}

/**
 * Publisher information for verified skills
 * NOTE: This data comes FROM the registry, not generated by Mother
 */
export interface SkillPublisher {
  name: string;
  url?: string;
  verified?: boolean;
}

/**
 * Agent compatibility matrix
 * NOTE: This data comes FROM the registry skill metadata
 */
export interface SkillCompatibility {
  claude?: boolean;
  copilot?: boolean;
  codex?: boolean;
  v0?: boolean;
}

/**
 * Registry skill metadata
 * 
 * Quality signals (downloads, stars, verified) are read FROM the registry
 * catalog. Mother MCP does not track or generate this data - it only
 * consumes and displays what the registry provides.
 * 
 * The agent_skills_directory catalog includes:
 * - Skill metadata from GitHub repos (Anthropic, OpenAI, GitHub, etc.)
 * - Provider information and source URLs
 * - Duplicate detection and similarity scores
 */
export interface RegistrySkill {
  name: string;
  path: string;
  version: string;
  description: string;
  triggers: SkillTrigger;
  dependencies?: string[];
  tags?: string[];
  last_updated?: string;
  
  // === Community quality signals ===
  // These fields are READ from the registry catalog, not generated by Mother
  downloads?: number;           // Install count (from registry stats)
  stars?: number;               // GitHub stars (from source repo)
  verified?: boolean;           // Verified badge (from registry curation)
  publisher?: SkillPublisher;   // Publisher info (from registry metadata)
  compatibility?: SkillCompatibility;  // Agent compatibility (from registry)
  repository?: string;          // Source repository URL
}

/**
 * Curated skill bundles for common use cases
 * 
 * Bundles are defined in the agent_skills_directory and consumed by Mother MCP.
 * Bundle data comes from: https://github.com/dmgrok/agent_skills_directory/bundles.json
 * 
 * Skills are referenced by their full ID (e.g., "anthropics/mcp-builder")
 */
export interface SkillBundle {
  id: string;                   // Unique bundle identifier (e.g., "fullstack-nextjs")
  name: string;                 // Display name (e.g., "Full-Stack Next.js")
  description: string;          // What this bundle is for
  skills: string[];             // List of skill IDs (e.g., "anthropics/mcp-builder")
  use_cases: string[];          // Example use cases
  icon?: string;                // Emoji or icon identifier
  tags?: string[];              // Categories like "frontend", "backend", "devops"
  category?: string;            // Bundle category (frontend, backend, etc.)
  downloads?: number;           // Bundle install count (from registry)
  verified?: boolean;           // Official/curated bundle (from registry)
}

export interface RegistryIndex {
  version: string;
  last_updated: string;
  skills: RegistrySkill[];
  bundles?: SkillBundle[];      // Optional curated bundles
}

// Detection types
export interface DetectedTechnology {
  id: string;
  name?: string;
  version?: string;
  confidence: number;
  source: string;
}

export interface DetectedStack {
  languages: DetectedTechnology[];
  frameworks: DetectedTechnology[];
  databases: DetectedTechnology[];
  infrastructure: DetectedTechnology[];
  tools: DetectedTechnology[];
}

// Installed skill types
export interface InstalledSkill {
  name: string;
  version: string;
  source: string;
  installed_at: string;
  path: string;
  last_updated?: string;
}

// Project context types
export interface ProjectContext {
  generated_at: string;
  detection_sources: string[];
  project: {
    name: string;
    description?: string;
  };
  detected: DetectedStack;
  installed_skills: InstalledSkill[];
  manual: {
    include_skills: string[];
    exclude_skills: string[];
    context_notes?: string;
  };
}

// Config types
export interface CacheConfig {
  refresh_interval_days: number;
  registry_cache: string;
  last_refresh?: string;
}

export interface DetectionConfig {
  enabled: boolean;
  sources: {
    type: string;
    patterns?: string[];
    file?: string;
    extract?: string[];
  }[];
}

export interface AgentOverride {
  install_path?: string;
}

export interface MotherConfig {
  version: string;
  agent: {
    mode: AgentMode;
    sync_both: boolean;
    force?: AgentId;
  };
  registry: RegistrySource[];
  install_path?: string;
  agent_overrides?: Record<string, AgentOverride>;
  cache: CacheConfig;
  detection: DetectionConfig;
  skills: {
    always_include: string[];
    always_exclude: string[];
  };
  sync: {
    auto_remove: boolean;
    prompt_on_changes: boolean;
  };
}

// Sync result types
export type SkillSource = 'manual' | 'discovery' | 'dependency';

export interface SkillChange {
  name: string;
  version: string;
  oldVersion?: string;
  source?: SkillSource;
  matchedBy?: string;
}

// Preview types for user validation
export interface PendingSkillChange extends SkillChange {
  action: 'add' | 'update' | 'remove';
  reason: string;
}

export interface SyncPreview {
  pending_changes: PendingSkillChange[];
  manual_skills: string[];
  discovered_skills: string[];
  requires_confirmation: boolean;
  preview_id: string;
}

export interface SyncResult {
  added: SkillChange[];
  updated: SkillChange[];
  removed: SkillChange[];
  unchanged: SkillChange[];
  agent: AgentId[];
  paths: string[];
  detected_stack: DetectedStack;
}

// Tool parameter types
export interface SyncSkillsParams {
  force_refresh?: boolean;
  dry_run?: boolean;
  agent?: AgentMode;
}

export interface SearchSkillsParams {
  query?: string;
  tags?: string[];
}

export interface InstallSkillParams {
  skill_name: string;
}

export interface UninstallSkillParams {
  skill_name: string;
}

export interface SetAgentPreferenceParams {
  agent: AgentMode;
}

export interface ConfirmSyncParams {
  preview_id: string;
  approved_skills?: string[];
  rejected_skills?: string[];
}

// GitHub SBOM types
export interface GitHubConfig {
  token?: string;
  owner?: string;
  repo?: string;
}

export interface SBOMPackage {
  name: string;
  version?: string;
  ecosystem: string;
  license?: string;
  relationship?: 'direct' | 'transitive';
  purl?: string;
}

export interface SBOMResult {
  packages: SBOMPackage[];
  source: 'github-sbom';
  fetchedAt: string;
}

// Enhanced detection config
export interface EnhancedDetectionConfig {
  useGitHubSBOM: boolean;
  useSpecfy: boolean;
  useLocalFallback: boolean;
  github?: GitHubConfig;
}

// Detection source tracking
export type DetectionSource = 'github-sbom' | 'specfy' | 'local';

export interface EnhancedDetectionResult {
  stack: DetectedStack;
  sources: DetectionSource[];
  packages?: SBOMPackage[];
  rawSpecfy?: unknown;
}
